import { style } from "@mui/system";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">My Clothing Brand App!</a>
        </h1>
        <br></br>
        <button className={styles.code}>
          <Link href="landing">start shopping </Link>
        </button>
      </main>
    </div>
  );
}
